### ISSUE TITLE
Github read-ability.

### ISSUE THREAD

**Issue by JohnPhoto** [tink-ab/tink-connect-example#2]
https://github.com/tink-ab/tink-connect-example/blob/master/client/src/Callback.js has an issue with the `'` which makes the file unnecessary hard to read. Consider changing `don't` to `do not`.

![screen shot 2018-04-19 at 08 40 45](https://user-images.githubusercontent.com/3659871/38975284-98d5ec92-43ad-11e8-912f-e41c7127cc68.png)

**Comment by bailer** [comment]
The reason it breaks is because Github doesn't parse it as JSX since it's written in a `.js` file instead of `.jsx`. See https://github.com/github/linguist/issues/3144 and https://github.com/github/linguist/pull/3677. 
I would consider converting the files to `.jsx` instead which also makes it easier for text editors to use the correct syntax highlighting.

**Comment by ninaolo** [comment]
This should have been solved in this PR: https://github.com/tink-ab/tink-connect-example/pull/6 🙂
